- name: EK HTMLCov
  # You may pin to the exact commit or the version.
  # uses: essentialkaos/htmlcov-action@592e64bff63f9868f3fb5d6824e4441799a7968e
  uses: essentialkaos/htmlcov-action@v1
  with:
    # Path to coverage profile
    profile: 
    # Path to directory with sources
    path: 
    # Output artifact name
    output: # optional, default is Coverage
    # Version of HTMLCov
    version: # optional, default is 1.0.1
    # Retention in days
    retention: # optional, default is 3
name: Jekyll site CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
